version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:

  BeforeInstall:
    - location: cicd/scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: cicd/scripts/after_install.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: cicd/scripts/validate.sh
      timeout: 120
      runas: root

  AfterAllowTraffic:
    - location: cicd/scripts/after_allow_traffic.sh
      timeout: 120
      runas: root
