version: 0.2

phases:

  pre_build:
    commands:
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $AWS_REGION_NAME | docker login --username AWS --password-stdin $ECR_REPO_URL
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - echo "Image tag - $IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t wordpress-app -f docker/Dockerfile .
      - echo "Docker build complete ✅"
      - docker tag wordpress-app:latest $ECR_REPO_URL:$IMAGE_TAG
      - docker tag wordpress-app:latest $ECR_REPO_URL:latest
      - docker push $ECR_REPO_URL:$IMAGE_TAG
      - docker push $ECR_REPO_URL:latest
      - echo "Image pushed to ECR ✅"
      - printf '[{"name":"wordpress","imageUri":"%s"}]' $ECR_REPO_URL:$IMAGE_TAG > imagedef.json

  post_build:
    commands:
      - echo "Build complete at $(date)"

artifacts:
  files:
    - imagedef.json
    - cicd/appspec.yml
    - cicd/scripts/**
  discard-paths: no
